package com.maodouchat.server.plugins

import com.maodouchat.server.service.CacheService
import com.maodouchat.server.service.RuntimeConfigService
import io.ktor.http.ContentType
import io.ktor.server.response.respondText
import io.ktor.server.application.call
import io.ktor.server.routing.Route
import io.ktor.server.routing.get
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonElement

/** 公开服务器状态：维护模式 / 功能开关快照（带缓存）。 */
internal fun Route.configureServerStatusRoutes(cacheService: CacheService) {
    get("/api/public/status") {
        val statusCacheKey = "public_status"
        cacheService.getPublicStatus(statusCacheKey)?.let { cached ->
            call.respondText(cached as String, ContentType.Application.Json)
            return@get
        }
        val maintenance = RuntimeConfigService.isMaintenanceMode()
        val registrationOpen = RuntimeConfigService.isRegistrationAllowed()
        val body = buildJsonObject {
            put("ok", !maintenance)
            put("maintenance", maintenance)
            put("maintenanceMessage", if (maintenance) RuntimeConfigService.get(RuntimeConfigService.KEY_MAINTENANCE_MESSAGE) else "")
            put("registrationOpen", registrationOpen)
            put("inviteOnlyHint", if (registrationOpen) "" else RuntimeConfigService.get(RuntimeConfigService.KEY_INVITE_ONLY_HINT))
            put("globalBanner", RuntimeConfigService.get(RuntimeConfigService.KEY_GLOBAL_BANNER))
            put("forceE2eeBanner", RuntimeConfigService.get(RuntimeConfigService.KEY_FORCE_E2EE_BANNER))
            put("sealedSenderEnabled", RuntimeConfigService.isSealedSenderEnabled())
            put("allowBots", RuntimeConfigService.isBotsAllowed())
            put("maxGroupSize", RuntimeConfigService.getInt(RuntimeConfigService.KEY_MAX_GROUP_SIZE, 200))
            put("maxMessagePerMin", RuntimeConfigService.maxMessagePerMinute())
            put("aiEnabled", RuntimeConfigService.isAiEnabled())
            put("publicAnnouncement", RuntimeConfigService.get(RuntimeConfigService.KEY_PUBLIC_ANNOUNCEMENT))
            put("pqxdhPreview", RuntimeConfigService.isPqxdhPreviewEnabled())
            put("minAppVersion", RuntimeConfigService.minAppVersion())
            put("captureAlertEnabled", RuntimeConfigService.isCaptureAlertEnabled())
            put("maxBotsPerUser", RuntimeConfigService.maxBotsPerUser())
            put("mediaUploadEnabled", RuntimeConfigService.isMediaUploadEnabled())
            put("groupPlayEnabled", RuntimeConfigService.isGroupPlayEnabled())
            put("linkPreviewEnabled", RuntimeConfigService.isLinkPreviewEnabled())
            put("voiceMessagesEnabled", RuntimeConfigService.isVoiceMessagesEnabled())
            put("reactionsEnabled", RuntimeConfigService.isReactionsEnabled())
            put("stickersEnabled", RuntimeConfigService.isStickersEnabled())
            put("silentSendEnabled", RuntimeConfigService.isSilentSendEnabled())
            put("callsEnabled", RuntimeConfigService.isCallsEnabled())
            put("scheduledMessagesEnabled", RuntimeConfigService.isScheduledMessagesEnabled())
            put("viewOnceEnabled", RuntimeConfigService.isViewOnceEnabled())
            put("liveLocationEnabled", RuntimeConfigService.isLiveLocationEnabled())
            put("markdownEnabled", RuntimeConfigService.isMarkdownEnabled())
            put("typingIndicatorsEnabled", RuntimeConfigService.isTypingIndicatorsEnabled())
            put("readReceiptsEnabled", RuntimeConfigService.isReadReceiptsEnabled())
            put("presenceEnabled", RuntimeConfigService.isPresenceEnabled())
            put("messageStarringEnabled", RuntimeConfigService.isMessageStarringEnabled())
            put("chatExportEnabled", RuntimeConfigService.isChatExportEnabled())
            put("messageForwardingEnabled", RuntimeConfigService.isMessageForwardingEnabled())
            put("globalSearchEnabled", RuntimeConfigService.isGlobalSearchEnabled())
            put("friendRequestsEnabled", RuntimeConfigService.isFriendRequestsEnabled())
            put("chatFoldersEnabled", RuntimeConfigService.isChatFoldersEnabled())
            put("postsEnabled", RuntimeConfigService.isPostsEnabled())
            put("blockReportEnabled", RuntimeConfigService.isBlockReportEnabled())
            put("chatArchiveEnabled", RuntimeConfigService.isChatArchiveEnabled())
            put("nearbyEnabled", RuntimeConfigService.isNearbyEnabled())
            put("chatPinEnabled", RuntimeConfigService.isChatPinEnabled())
            put("markedUnreadEnabled", RuntimeConfigService.isMarkedUnreadEnabled())
            put("chatMuteEnabled", RuntimeConfigService.isChatMuteEnabled())
            put("disappearingMessagesEnabled", RuntimeConfigService.isDisappearingMessagesEnabled())
            put("chatLockEnabled", RuntimeConfigService.isChatLockEnabled())
            put("messageEditEnabled", RuntimeConfigService.isMessageEditEnabled())
            put("messagePinEnabled", RuntimeConfigService.isMessagePinEnabled())
            put("messageRevokeEnabled", RuntimeConfigService.isMessageRevokeEnabled())
            put("pollsEnabled", RuntimeConfigService.isPollsEnabled())
            put("appLockEnabled", RuntimeConfigService.isAppLockEnabled())
            put("chatDraftsEnabled", RuntimeConfigService.isChatDraftsEnabled())
            put("groupInvitesEnabled", RuntimeConfigService.isGroupInvitesEnabled())
            put("mentionsEnabled", RuntimeConfigService.isMentionsEnabled())
            put("nudgeEnabled", RuntimeConfigService.isNudgeEnabled())
            put("safetyCodeEnabled", RuntimeConfigService.isSafetyCodeEnabled())
            put("qrCodeEnabled", RuntimeConfigService.isQrCodeEnabled())
            put("contactCardEnabled", RuntimeConfigService.isContactCardEnabled())
            put("spoilerMediaEnabled", RuntimeConfigService.isSpoilerMediaEnabled())
            put("autoDownloadEnabled", RuntimeConfigService.isAutoDownloadEnabled())
            put("staticLocationEnabled", RuntimeConfigService.isStaticLocationEnabled())
            put("fileShareEnabled", RuntimeConfigService.isFileShareEnabled())
            put("secretChatEnabled", RuntimeConfigService.isSecretChatEnabled())
            put("screenSecureRuntimeEnabled", RuntimeConfigService.isScreenSecureRuntimeEnabled())
            put("imageSendEnabled", RuntimeConfigService.isImageSendEnabled())
            put("videoSendEnabled", RuntimeConfigService.isVideoSendEnabled())
            put("gifSendEnabled", RuntimeConfigService.isGifSendEnabled())
            put("blindWatermarkEnabled", RuntimeConfigService.isBlindWatermarkEnabled())
            put("voiceCallEnabled", RuntimeConfigService.isVoiceCallEnabled())
            put("videoCallEnabled", RuntimeConfigService.isVideoCallEnabled())
            put("chatWallpaperEnabled", RuntimeConfigService.isChatWallpaperEnabled())
            put("chatFontScaleEnabled", RuntimeConfigService.isChatFontScaleEnabled())
            put("unreadPriorityEnabled", RuntimeConfigService.isUnreadPriorityEnabled())
            put("ringtoneEnabled", RuntimeConfigService.isRingtoneEnabled())
            put("notificationSoundEnabled", RuntimeConfigService.isNotificationSoundEnabled())
            put("notificationPreviewEnabled", RuntimeConfigService.isNotificationPreviewEnabled())
            put("pushNotificationsEnabled", RuntimeConfigService.isPushNotificationsEnabled())
            put("taskRemindersEnabled", RuntimeConfigService.isTaskRemindersEnabled())
            put("dndEnabled", RuntimeConfigService.isDndEnabled())
            put("inAppSoundsEnabled", RuntimeConfigService.isInAppSoundsEnabled())
            put("hapticsEnabled", RuntimeConfigService.isHapticsEnabled())
            put("chatAnimationsEnabled", RuntimeConfigService.isChatAnimationsEnabled())
            put("navTransitionsEnabled", RuntimeConfigService.isNavTransitionsEnabled())
            put("screenshotDetectEnabled", RuntimeConfigService.isScreenshotDetectEnabled())
            put("recentsExclusionEnabled", RuntimeConfigService.isRecentsExclusionEnabled())
            put("secretCopyBlockEnabled", RuntimeConfigService.isSecretCopyBlockEnabled())
            put("secretMediaExportBlockEnabled", RuntimeConfigService.isSecretMediaExportBlockEnabled())
            put("secretForwardBlockEnabled", RuntimeConfigService.isSecretForwardBlockEnabled())
            put("secretChatExportBlockEnabled", RuntimeConfigService.isSecretChatExportBlockEnabled())
            put("secretAutoDisappearEnabled", RuntimeConfigService.isSecretAutoDisappearEnabled())
            put("secretLinkPreviewBlockEnabled", RuntimeConfigService.isSecretLinkPreviewBlockEnabled())
            put("secretExternalLinkBlockEnabled", RuntimeConfigService.isSecretExternalLinkBlockEnabled())
            put("secretNotifPreviewBlockEnabled", RuntimeConfigService.isSecretNotifPreviewBlockEnabled())
            put("secretListPreviewBlockEnabled", RuntimeConfigService.isSecretListPreviewBlockEnabled())
            put("secretReactionBlockEnabled", RuntimeConfigService.isSecretReactionBlockEnabled())
            put("secretStarBlockEnabled", RuntimeConfigService.isSecretStarBlockEnabled())
            put("secretTypingBlockEnabled", RuntimeConfigService.isSecretTypingBlockEnabled())
            put("secretReadReceiptBlockEnabled", RuntimeConfigService.isSecretReadReceiptBlockEnabled())
            put("secretPresenceBlockEnabled", RuntimeConfigService.isSecretPresenceBlockEnabled())
            put("secretLastSeenBlockEnabled", RuntimeConfigService.isSecretLastSeenBlockEnabled())
            putJsonElement("secretSurfaceFlags", publicSecretSurfaceFlags())
            put("serverTime", System.currentTimeMillis())
        }.toString()
        cacheService.putPublicStatus(statusCacheKey, body)
        call.respondText(body, ContentType.Application.Json)
    }
}
