package com.maodouchat.util

import org.json.JSONArray
import org.json.JSONObject
import kotlin.random.Random

/**
 * Group play helpers (polls, dice, check-in) — pure/local formatting.
 * Poll persistence is server-backed; dice is ephemeral system text with optional E2EE payload.
 */
object GroupPlayPolicy {
    const val DICE_PREFIX = "DICE:"
    const val POLL_PREFIX = "POLL:"
    const val CHECKIN_PREFIX = "CHECKIN:"

    fun rollDice(sides: Int = 6): Int {
        val s = sides.coerceIn(2, 100)
        return Random.nextInt(1, s + 1)
    }

    fun formatDiceMessage(value: Int, sides: Int = 6, rollerName: String = ""): String {
        val who = rollerName.takeIf { it.isNotBlank() }?.let { "$it " }.orEmpty()
        return "${DICE_PREFIX}$sides:$value|${who}rolled $value / $sides"
    }

    fun parseDice(content: String): Pair<Int, Int>? {
        if (!content.startsWith(DICE_PREFIX)) return null
        val body = content.removePrefix(DICE_PREFIX)
        val head = GroupPlayFieldEscape.unesc(body.substringBefore('|'))
        val parts = head.split(':')
        if (parts.size < 2) return null
        val sides = parts[0].toIntOrNull() ?: return null
        val value = parts[1].toIntOrNull() ?: return null
        return sides to value
    }

    fun formatCheckIn(dayStreak: Int, userLabel: String): String =
        com.maodouchat.group.play.GroupCheckinPolicy.formatCheckIn(dayStreak, userLabel)

    fun buildPollPayload(
        pollId: String,
        question: String,
        options: List<String>,
        multi: Boolean,
        anonymous: Boolean
    ): String = com.maodouchat.group.play.GroupPollPolicy.buildPollPayload(pollId, question, options, multi, anonymous)

    fun parsePoll(content: String): JSONObject? =
        com.maodouchat.group.play.GroupPollPolicy.parsePoll(content)

    fun formatLuckyDraw(pickerName: String, targetName: String): String {
        return "LUCKY:${GroupPlayFieldEscape.esc(pickerName)}|$targetName"
    }

    fun parseLuckyDraw(content: String): Pair<String, String>? {
        if (!content.startsWith("LUCKY:")) return null
        val body = content.removePrefix("LUCKY:")
        val a = GroupPlayFieldEscape.unesc(body.substringBefore('|'))
        val b = body.substringAfter('|', "")
        if (a.isBlank() || b.isBlank()) return null
        return a to b
    }

    const val RPS_PREFIX = GroupPlayClassicDelegates.RPS_PREFIX
    const val TRUTH_PREFIX = GroupPlayClassicDelegates.TRUTH_PREFIX
    const val ANON_PREFIX = GroupPlayClassicDelegates.ANON_PREFIX
    fun rollRps(): String = GroupPlayClassicDelegates.rollRps()
    fun formatRps(choice: String, userLabel: String): String = GroupPlayClassicDelegates.formatRps(choice, userLabel)
    fun parseRps(content: String): String? = GroupPlayClassicDelegates.parseRps(content)
    const val BOMB_PREFIX = GroupPlayClassicDelegates.BOMB_PREFIX
    const val WORD_PREFIX = GroupPlayClassicDelegates.WORD_PREFIX
    fun rollNumberBomb(max: Int = 100): Pair<Int, Int> = GroupPlayClassicDelegates.rollNumberBomb(max)
    fun formatNumberBomb(secret: Int, max: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatNumberBomb(secret, max, hostLabel)
    fun parseNumberBomb(content: String): Triple<Int, Int, String>? = GroupPlayClassicDelegates.parseNumberBomb(content)
    fun randomWordSeed(): String = GroupPlayClassicDelegates.randomWordSeed()
    fun formatWordChain(seed: String, userLabel: String): String = GroupPlayClassicDelegates.formatWordChain(seed, userLabel)
    const val RACE_PREFIX = GroupPlayClassicDelegates.RACE_PREFIX
    fun randomRaceToken(): String = GroupPlayClassicDelegates.randomRaceToken()
    fun formatReactionRace(token: String, hostLabel: String): String = GroupPlayClassicDelegates.formatReactionRace(token, hostLabel)
    fun parseReactionRace(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseReactionRace(content)
    const val WOULD_PREFIX = GroupPlayClassicDelegates.WOULD_PREFIX
    const val EMOJI_RAIN_PREFIX = GroupPlayClassicDelegates.EMOJI_RAIN_PREFIX
    fun formatWouldYouRather(a: String, b: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWouldYouRather(a, b, hostLabel)
    fun parseWouldYouRather(content: String): Triple<String, String, String>? = GroupPlayClassicDelegates.parseWouldYouRather(content)
    fun formatEmojiRain(hostLabel: String, emoji: String = rainEmojis.random()): String = GroupPlayClassicDelegates.formatEmojiRain(hostLabel, emoji)
    fun parseEmojiRain(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseEmojiRain(content)
    const val TRUTHS_PREFIX = GroupPlayClassicDelegates.TRUTHS_PREFIX
    const val QUIZ_PREFIX = GroupPlayClassicDelegates.QUIZ_PREFIX
    fun formatTwoTruthsOneLie(t1: String, t2: String, lie: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTwoTruthsOneLie(t1, t2, lie, hostLabel)
    fun parseTwoTruthsOneLie(content: String): List<String>? = GroupPlayClassicDelegates.parseTwoTruthsOneLie(content)
    fun formatQuiz(question: String, answer: String, options: List<String>, hostLabel: String): String = GroupPlayClassicDelegates.formatQuiz(question, answer, options, hostLabel)
    fun parseQuiz(content: String): Triple<String, String, List<String>>? = GroupPlayClassicDelegates.parseQuiz(content)
    const val SPIN_PREFIX = GroupPlayClassicDelegates.SPIN_PREFIX
    const val STORY_PREFIX = GroupPlayClassicDelegates.STORY_PREFIX
    const val COUNTDOWN_PREFIX = GroupPlayClassicDelegates.COUNTDOWN_PREFIX
    fun spinWheel(): String = GroupPlayClassicDelegates.spinWheel()
    fun formatSpin(result: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSpin(result, hostLabel)
    fun parseSpin(content: String): String? = GroupPlayClassicDelegates.parseSpin(content)
    fun formatStory(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatStory(seed, hostLabel)
    fun parseStory(content: String): String? = GroupPlayClassicDelegates.parseStory(content)
    fun formatCountdown(seconds: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatCountdown(seconds, hostLabel)
    fun parseCountdown(content: String): Int? = GroupPlayClassicDelegates.parseCountdown(content)
    const val BINGO_PREFIX = GroupPlayClassicDelegates.BINGO_PREFIX
    const val LOTTERY_PREFIX = GroupPlayClassicDelegates.LOTTERY_PREFIX
    const val HOTSEAT_PREFIX = GroupPlayClassicDelegates.HOTSEAT_PREFIX
    fun formatBingo(board: List<String>, hostLabel: String): String = GroupPlayClassicDelegates.formatBingo(board, hostLabel)
    fun parseBingo(content: String): List<String>? = GroupPlayClassicDelegates.parseBingo(content)
    fun formatLottery(pool: List<String>, winner: String, hostLabel: String): String = GroupPlayClassicDelegates.formatLottery(pool, winner, hostLabel)
    fun parseLottery(content: String): Pair<String, List<String>>? = GroupPlayClassicDelegates.parseLottery(content)
    fun formatHotSeat(target: String, hostLabel: String): String = GroupPlayClassicDelegates.formatHotSeat(target, hostLabel)
    fun parseHotSeat(content: String): String? = GroupPlayClassicDelegates.parseHotSeat(content)
    const val COINFLIP_PREFIX = GroupPlayClassicDelegates.COINFLIP_PREFIX
    const val REDPACKET_PREFIX = GroupPlayClassicDelegates.REDPACKET_PREFIX
    fun formatCoinFlip(side: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCoinFlip(side, hostLabel)
    fun parseCoinFlip(content: String): String? = GroupPlayClassicDelegates.parseCoinFlip(content)
    fun formatRedPacketJoke(amountLabel: String, hostLabel: String): String = GroupPlayClassicDelegates.formatRedPacketJoke(amountLabel, hostLabel)
    fun parseRedPacketJoke(content: String): String? = GroupPlayClassicDelegates.parseRedPacketJoke(content)
    const val CHARADES_PREFIX = GroupPlayClassicDelegates.CHARADES_PREFIX
    const val NUMBERGUESS_PREFIX = GroupPlayClassicDelegates.NUMBERGUESS_PREFIX
    fun formatCharades(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCharades(prompt, hostLabel)
    fun parseCharades(content: String): String? = GroupPlayClassicDelegates.parseCharades(content)
    fun formatNumberGuess(secret: Int, max: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatNumberGuess(secret, max, hostLabel)
    fun parseNumberGuess(content: String): Pair<Int, Int>? = GroupPlayClassicDelegates.parseNumberGuess(content)
    const val IMPOSTOR_PREFIX = GroupPlayClassicDelegates.IMPOSTOR_PREFIX
    const val RIDDLE_PREFIX = GroupPlayClassicDelegates.RIDDLE_PREFIX
    const val EMOJI_STORY_PREFIX = GroupPlayClassicDelegates.EMOJI_STORY_PREFIX
    fun formatRiddle(q: String, a: String, hostLabel: String): String = GroupPlayClassicDelegates.formatRiddle(q, a, hostLabel)
    fun parseRiddle(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseRiddle(content)
    fun formatImpostor(word: String, hostLabel: String): String = GroupPlayClassicDelegates.formatImpostor(word, hostLabel)
    fun parseImpostor(content: String): String? = GroupPlayClassicDelegates.parseImpostor(content)
    fun formatEmojiStory(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiStory(seed, hostLabel)
    fun parseEmojiStory(content: String): String? = GroupPlayClassicDelegates.parseEmojiStory(content)
    const val SIMON_PREFIX = GroupPlayClassicDelegates.SIMON_PREFIX
    const val HOTORNOT_PREFIX = GroupPlayClassicDelegates.HOTORNOT_PREFIX
    const val ALPHABET_PREFIX = GroupPlayClassicDelegates.ALPHABET_PREFIX
    fun formatSimon(seq: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSimon(seq, hostLabel)
    fun parseSimon(content: String): String? = GroupPlayClassicDelegates.parseSimon(content)
    fun formatHotOrNot(topic: String, hostLabel: String): String = GroupPlayClassicDelegates.formatHotOrNot(topic, hostLabel)
    fun parseHotOrNot(content: String): String? = GroupPlayClassicDelegates.parseHotOrNot(content)
    fun formatAlphabet(letter: String, hostLabel: String): String = GroupPlayClassicDelegates.formatAlphabet(letter, hostLabel)
    fun parseAlphabet(content: String): String? = GroupPlayClassicDelegates.parseAlphabet(content)
    const val TRIVIA_PREFIX = GroupPlayClassicDelegates.TRIVIA_PREFIX
    const val SPEED_PREFIX = GroupPlayClassicDelegates.SPEED_PREFIX
    fun formatTrivia(q: String, a: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTrivia(q, a, hostLabel)
    fun parseTrivia(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseTrivia(content)
    fun formatSpeedChallenge(sec: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatSpeedChallenge(sec, hostLabel)
    fun parseSpeedChallenge(content: String): Int? = GroupPlayClassicDelegates.parseSpeedChallenge(content)
    const val TRUTH_OR_DARE_PREFIX = GroupPlayClassicDelegates.TRUTH_OR_DARE_PREFIX
    const val NEVER_HAVE_PREFIX = GroupPlayClassicDelegates.NEVER_HAVE_PREFIX
    const val MEMORY_MATCH_PREFIX = GroupPlayClassicDelegates.MEMORY_MATCH_PREFIX
    const val DRAW_PROMPT_PREFIX = GroupPlayClassicDelegates.DRAW_PROMPT_PREFIX
    fun randomMemoryBoard(): String = GroupPlayClassicDelegates.randomMemoryBoard()
    fun formatTruthOrDare(mode: String, prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTruthOrDare(mode, prompt, hostLabel)
    fun parseTruthOrDare(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseTruthOrDare(content)
    fun formatNeverHaveIEver(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatNeverHaveIEver(prompt, hostLabel)
    fun parseNeverHaveIEver(content: String): String? = GroupPlayClassicDelegates.parseNeverHaveIEver(content)
    fun formatMemoryMatch(board: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMemoryMatch(board, hostLabel)
    fun parseMemoryMatch(content: String): String? = GroupPlayClassicDelegates.parseMemoryMatch(content)
    fun formatDrawPrompt(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatDrawPrompt(prompt, hostLabel)
    fun parseDrawPrompt(content: String): String? = GroupPlayClassicDelegates.parseDrawPrompt(content)
    const val ICEBREAKER_PREFIX = GroupPlayClassicDelegates.ICEBREAKER_PREFIX
    const val EMOJI_DUEL_PREFIX = GroupPlayClassicDelegates.EMOJI_DUEL_PREFIX
    const val RAPID_FIRE_PREFIX = GroupPlayClassicDelegates.RAPID_FIRE_PREFIX
    fun randomEmojiDuel(): String = GroupPlayClassicDelegates.randomEmojiDuel()
    fun formatIcebreaker(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatIcebreaker(prompt, hostLabel)
    fun parseIcebreaker(content: String): String? = GroupPlayClassicDelegates.parseIcebreaker(content)
    fun formatEmojiDuel(pair: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiDuel(pair, hostLabel)
    fun parseEmojiDuel(content: String): String? = GroupPlayClassicDelegates.parseEmojiDuel(content)
    fun formatRapidFire(topic: String, hostLabel: String): String = GroupPlayClassicDelegates.formatRapidFire(topic, hostLabel)
    fun parseRapidFire(content: String): String? = GroupPlayClassicDelegates.parseRapidFire(content)
    const val SCATTER_PREFIX = GroupPlayClassicDelegates.SCATTER_PREFIX
    const val MINUTE_TALK_PREFIX = GroupPlayClassicDelegates.MINUTE_TALK_PREFIX
    const val CAPTION_THIS_PREFIX = GroupPlayClassicDelegates.CAPTION_THIS_PREFIX
    fun formatScatter(letter: String, category: String, hostLabel: String): String = GroupPlayClassicDelegates.formatScatter(letter, category, hostLabel)
    fun parseScatter(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseScatter(content)
    fun formatMinuteTalk(topic: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMinuteTalk(topic, hostLabel)
    fun parseMinuteTalk(content: String): String? = GroupPlayClassicDelegates.parseMinuteTalk(content)
    fun formatCaptionThis(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCaptionThis(seed, hostLabel)
    fun parseCaptionThis(content: String): String? = GroupPlayClassicDelegates.parseCaptionThis(content)
    const val STORY_SWAP_PREFIX = GroupPlayClassicDelegates.STORY_SWAP_PREFIX
    const val KARAOKE_PREFIX = GroupPlayClassicDelegates.KARAOKE_PREFIX
    const val BLIND_Q_PREFIX = GroupPlayClassicDelegates.BLIND_Q_PREFIX
    fun formatStorySwap(opener: String, hostLabel: String): String = GroupPlayClassicDelegates.formatStorySwap(opener, hostLabel)
    fun parseStorySwap(content: String): String? = GroupPlayClassicDelegates.parseStorySwap(content)
    fun formatKaraoke(line: String, hostLabel: String): String = GroupPlayClassicDelegates.formatKaraoke(line, hostLabel)
    fun parseKaraoke(content: String): String? = GroupPlayClassicDelegates.parseKaraoke(content)
    fun formatBlindQ(q: String, hostLabel: String): String = GroupPlayClassicDelegates.formatBlindQ(q, hostLabel)
    fun parseBlindQ(content: String): String? = GroupPlayClassicDelegates.parseBlindQ(content)
    const val FORTUNE_PREFIX = GroupPlayClassicDelegates.FORTUNE_PREFIX
    const val EMOJI_QUIZ_PREFIX = GroupPlayClassicDelegates.EMOJI_QUIZ_PREFIX
    const val CHAIN_REACT_PREFIX = GroupPlayClassicDelegates.CHAIN_REACT_PREFIX
    fun randomChainSeed(): String = GroupPlayClassicDelegates.randomChainSeed()
    fun formatFortune(text: String, hostLabel: String): String = GroupPlayClassicDelegates.formatFortune(text, hostLabel)
    fun parseFortune(content: String): String? = GroupPlayClassicDelegates.parseFortune(content)
    fun formatEmojiQuiz(prompt: String, answer: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiQuiz(prompt, answer, hostLabel)
    fun parseEmojiQuiz(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseEmojiQuiz(content)
    fun formatChainReact(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatChainReact(seed, hostLabel)
    fun parseChainReact(content: String): String? = GroupPlayClassicDelegates.parseChainReact(content)
    const val DEBATE_PREFIX = GroupPlayClassicDelegates.DEBATE_PREFIX
    const val MIRROR_PREFIX = GroupPlayClassicDelegates.MIRROR_PREFIX
    const val HIDESEEK_PREFIX = GroupPlayClassicDelegates.HIDESEEK_PREFIX
    const val TOAST_PREFIX = GroupPlayClassicDelegates.TOAST_PREFIX
    fun randomHideEmoji(): String = GroupPlayClassicDelegates.randomHideEmoji()
    fun formatDebate(topic: String, hostLabel: String): String = GroupPlayClassicDelegates.formatDebate(topic, hostLabel)
    fun parseDebate(content: String): String? = GroupPlayClassicDelegates.parseDebate(content)
    fun formatMirror(line: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMirror(line, hostLabel)
    fun parseMirror(content: String): String? = GroupPlayClassicDelegates.parseMirror(content)
    fun formatHideSeek(emoji: String, hostLabel: String): String = GroupPlayClassicDelegates.formatHideSeek(emoji, hostLabel)
    fun parseHideSeek(content: String): String? = GroupPlayClassicDelegates.parseHideSeek(content)
    fun formatToast(line: String, hostLabel: String): String = GroupPlayClassicDelegates.formatToast(line, hostLabel)
    fun parseToast(content: String): String? = GroupPlayClassicDelegates.parseToast(content)
    const val HOTPOTATO_PREFIX = GroupPlayClassicDelegates.HOTPOTATO_PREFIX
    const val WORDHINT_PREFIX = GroupPlayClassicDelegates.WORDHINT_PREFIX
    fun formatHotPotato(seconds: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatHotPotato(seconds, hostLabel)
    fun parseHotPotato(content: String): Int? = GroupPlayClassicDelegates.parseHotPotato(content)
    fun formatWordHint(hint: String, answer: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWordHint(hint, answer, hostLabel)
    fun parseWordHint(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseWordHint(content)
    const val SPYFALL_PREFIX = GroupPlayClassicDelegates.SPYFALL_PREFIX
    const val ACROSTIC_PREFIX = GroupPlayClassicDelegates.ACROSTIC_PREFIX
    const val EMOJI_TR_PREFIX = GroupPlayClassicDelegates.EMOJI_TR_PREFIX
    fun formatSpyfall(location: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSpyfall(location, hostLabel)
    fun parseSpyfall(content: String): String? = GroupPlayClassicDelegates.parseSpyfall(content)
    fun formatAcrostic(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatAcrostic(seed, hostLabel)
    fun parseAcrostic(content: String): String? = GroupPlayClassicDelegates.parseAcrostic(content)
    fun formatEmojiTranslate(prompt: String, answer: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiTranslate(prompt, answer, hostLabel)
    fun parseEmojiTranslate(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseEmojiTranslate(content)
    const val TWENTYQ_PREFIX = GroupPlayClassicDelegates.TWENTYQ_PREFIX
    const val RHYME_PREFIX = GroupPlayClassicDelegates.RHYME_PREFIX
    const val ODDONE_PREFIX = GroupPlayClassicDelegates.ODDONE_PREFIX
    fun formatTwentyQuestions(subject: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTwentyQuestions(subject, hostLabel)
    fun parseTwentyQuestions(content: String): String? = GroupPlayClassicDelegates.parseTwentyQuestions(content)
    fun formatRhyme(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatRhyme(seed, hostLabel)
    fun parseRhyme(content: String): String? = GroupPlayClassicDelegates.parseRhyme(content)
    fun formatOddOneOut(options: String, answer: String, hostLabel: String): String = GroupPlayClassicDelegates.formatOddOneOut(options, answer, hostLabel)
    fun parseOddOneOut(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseOddOneOut(content)
    const val CATEGORIES_PREFIX = GroupPlayClassicDelegates.CATEGORIES_PREFIX
    const val PASSWORD_PREFIX = GroupPlayClassicDelegates.PASSWORD_PREFIX
    const val TIMECAPSULE_PREFIX = GroupPlayClassicDelegates.TIMECAPSULE_PREFIX
    fun formatCategories(cat: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCategories(cat, hostLabel)
    fun parseCategories(content: String): String? = GroupPlayClassicDelegates.parseCategories(content)
    fun formatPasswordGame(hint: String, hostLabel: String): String = GroupPlayClassicDelegates.formatPasswordGame(hint, hostLabel)
    fun parsePasswordGame(content: String): String? = GroupPlayClassicDelegates.parsePasswordGame(content)
    fun formatTimeCapsule(note: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTimeCapsule(note, hostLabel)
    fun parseTimeCapsule(content: String): String? = GroupPlayClassicDelegates.parseTimeCapsule(content)
    const val TABOO_PREFIX = GroupPlayClassicDelegates.TABOO_PREFIX
    const val LIGHTNING_PREFIX = GroupPlayClassicDelegates.LIGHTNING_PREFIX
    const val TWO_WORDS_PREFIX = GroupPlayClassicDelegates.TWO_WORDS_PREFIX
    fun formatTaboo(card: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTaboo(card, hostLabel)
    fun parseTaboo(content: String): String? = GroupPlayClassicDelegates.parseTaboo(content)
    fun formatLightning(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatLightning(prompt, hostLabel)
    fun parseLightning(content: String): String? = GroupPlayClassicDelegates.parseLightning(content)
    fun formatTwoWords(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTwoWords(seed, hostLabel)
    fun parseTwoWords(content: String): String? = GroupPlayClassicDelegates.parseTwoWords(content)
    const val WHISPER_PREFIX = GroupPlayClassicDelegates.WHISPER_PREFIX
    const val COUNTDOWN_RACE_PREFIX = GroupPlayClassicDelegates.COUNTDOWN_RACE_PREFIX
    fun formatWhisper(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWhisper(prompt, hostLabel)
    fun parseWhisper(content: String): String? = GroupPlayClassicDelegates.parseWhisper(content)
    fun formatCountdownRace(seconds: Int, hostLabel: String): String = GroupPlayClassicDelegates.formatCountdownRace(seconds, hostLabel)
    fun parseCountdownRace(content: String): String? = GroupPlayClassicDelegates.parseCountdownRace(content)
    const val EMOJI_MEMORY_PREFIX = GroupPlayClassicDelegates.EMOJI_MEMORY_PREFIX
    const val GEO_GUESS_PREFIX = GroupPlayClassicDelegates.GEO_GUESS_PREFIX
    fun formatEmojiMemory(board: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiMemory(board, hostLabel)
    fun parseEmojiMemory(content: String): String? = GroupPlayClassicDelegates.parseEmojiMemory(content)
    fun formatGeoGuess(clue: String, hostLabel: String): String = GroupPlayClassicDelegates.formatGeoGuess(clue, hostLabel)
    fun parseGeoGuess(content: String): String? = GroupPlayClassicDelegates.parseGeoGuess(content)
    const val ONE_WORD_PREFIX = GroupPlayClassicDelegates.ONE_WORD_PREFIX
    const val SPEED_MATH_PREFIX = GroupPlayClassicDelegates.SPEED_MATH_PREFIX
    const val STORY_SEED_PREFIX = GroupPlayClassicDelegates.STORY_SEED_PREFIX
    fun formatOneWord(word: String, hostLabel: String): String = GroupPlayClassicDelegates.formatOneWord(word, hostLabel)
    fun parseOneWord(content: String): String? = GroupPlayClassicDelegates.parseOneWord(content)
    fun formatSpeedMath(q: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSpeedMath(q, hostLabel)
    fun parseSpeedMath(content: String): String? = GroupPlayClassicDelegates.parseSpeedMath(content)
    fun formatStorySeed(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatStorySeed(seed, hostLabel)
    fun parseStorySeed(content: String): String? = GroupPlayClassicDelegates.parseStorySeed(content)
    const val WOULD_YOU_PREFIX2 = GroupPlayClassicDelegates.WOULD_YOU_PREFIX2
    const val EMOJI_ONLY_PREFIX = GroupPlayClassicDelegates.EMOJI_ONLY_PREFIX
    const val BLIND_DRAW_PREFIX = GroupPlayClassicDelegates.BLIND_DRAW_PREFIX
    fun formatWould2(a: String, b: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWould2(a, b, hostLabel)
    fun parseWould2(content: String): Pair<String, String>? = GroupPlayClassicDelegates.parseWould2(content)
    fun formatEmojiOnly(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiOnly(prompt, hostLabel)
    fun parseEmojiOnly(content: String): String? = GroupPlayClassicDelegates.parseEmojiOnly(content)
    fun formatBlindDraw(token: String, hostLabel: String): String = GroupPlayClassicDelegates.formatBlindDraw(token, hostLabel)
    fun parseBlindDraw(content: String): String? = GroupPlayClassicDelegates.parseBlindDraw(content)
    const val ALPHABET_RACE_PREFIX = GroupPlayClassicDelegates.ALPHABET_RACE_PREFIX
    const val SILENT_MOVIE_PREFIX = GroupPlayClassicDelegates.SILENT_MOVIE_PREFIX
    const val COLOR_WORD_PREFIX = GroupPlayClassicDelegates.COLOR_WORD_PREFIX
    fun formatAlphabetRace(start: String, hostLabel: String): String = GroupPlayClassicDelegates.formatAlphabetRace(start, hostLabel)
    fun parseAlphabetRace(content: String): String? = GroupPlayClassicDelegates.parseAlphabetRace(content)
    fun formatSilentMovie(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSilentMovie(prompt, hostLabel)
    fun parseSilentMovie(content: String): String? = GroupPlayClassicDelegates.parseSilentMovie(content)
    fun formatColorWord(pair: String, hostLabel: String): String = GroupPlayClassicDelegates.formatColorWord(pair, hostLabel)
    fun parseColorWord(content: String): String? = GroupPlayClassicDelegates.parseColorWord(content)
    const val DEBATE_FLASH_PREFIX = GroupPlayClassicDelegates.DEBATE_FLASH_PREFIX
    const val QUICK_POLL_PREFIX = GroupPlayClassicDelegates.QUICK_POLL_PREFIX
    fun formatDebateFlash(topic: String, hostLabel: String): String = GroupPlayClassicDelegates.formatDebateFlash(topic, hostLabel)
    fun parseDebateFlash(content: String): String? = GroupPlayClassicDelegates.parseDebateFlash(content)
    fun formatQuickPoll(options: String, hostLabel: String): String = GroupPlayClassicDelegates.formatQuickPoll(options, hostLabel)
    fun parseQuickPoll(content: String): String? = GroupPlayClassicDelegates.parseQuickPoll(content)
    const val MIRROR_ECHO_PREFIX = GroupPlayClassicDelegates.MIRROR_ECHO_PREFIX
    const val SYNC_CLAP_PREFIX = GroupPlayClassicDelegates.SYNC_CLAP_PREFIX
    const val FACT_OR_FICTION_PREFIX = GroupPlayClassicDelegates.FACT_OR_FICTION_PREFIX
    fun formatMirrorEcho(line: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMirrorEcho(line, hostLabel)
    fun parseMirrorEcho(content: String): String? = GroupPlayClassicDelegates.parseMirrorEcho(content)
    fun formatSyncClap(count: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSyncClap(count, hostLabel)
    fun parseSyncClap(content: String): String? = GroupPlayClassicDelegates.parseSyncClap(content)
    fun formatFactOrFiction(item: String, hostLabel: String): String = GroupPlayClassicDelegates.formatFactOrFiction(item, hostLabel)
    fun parseFactOrFiction(content: String): String? = GroupPlayClassicDelegates.parseFactOrFiction(content)
    const val IMPULSE_DRAW_PREFIX = GroupPlayClassicDelegates.IMPULSE_DRAW_PREFIX
    const val WORD_SCRAMBLE_PREFIX = GroupPlayClassicDelegates.WORD_SCRAMBLE_PREFIX
    const val REACTION_DUEL_PREFIX = GroupPlayClassicDelegates.REACTION_DUEL_PREFIX
    fun formatImpulseDraw(token: String, hostLabel: String): String = GroupPlayClassicDelegates.formatImpulseDraw(token, hostLabel)
    fun parseImpulseDraw(content: String): String? = GroupPlayClassicDelegates.parseImpulseDraw(content)
    fun formatWordScramble(pair: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWordScramble(pair, hostLabel)
    fun parseWordScramble(content: String): String? = GroupPlayClassicDelegates.parseWordScramble(content)
    fun formatReactionDuel(pair: String, hostLabel: String): String = GroupPlayClassicDelegates.formatReactionDuel(pair, hostLabel)
    fun parseReactionDuel(content: String): String? = GroupPlayClassicDelegates.parseReactionDuel(content)
    const val CODE_BREAKER_PREFIX = GroupPlayClassicDelegates.CODE_BREAKER_PREFIX
    const val SILLY_LAW_PREFIX = GroupPlayClassicDelegates.SILLY_LAW_PREFIX
    const val EMOJI_MATH_PREFIX = GroupPlayClassicDelegates.EMOJI_MATH_PREFIX
    fun formatCodeBreaker(code: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCodeBreaker(code, hostLabel)
    fun parseCodeBreaker(content: String): String? = GroupPlayClassicDelegates.parseCodeBreaker(content)
    fun formatSillyLaw(law: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSillyLaw(law, hostLabel)
    fun parseSillyLaw(content: String): String? = GroupPlayClassicDelegates.parseSillyLaw(content)
    fun formatEmojiMath(expr: String, hostLabel: String): String = GroupPlayClassicDelegates.formatEmojiMath(expr, hostLabel)
    fun parseEmojiMath(content: String): String? = GroupPlayClassicDelegates.parseEmojiMath(content)
    const val PIN_THE_MOOD_PREFIX = GroupPlayClassicDelegates.PIN_THE_MOOD_PREFIX
    const val REVOKE_RUSH_PREFIX = GroupPlayClassicDelegates.REVOKE_RUSH_PREFIX
    const val SECRET_SIGNAL_PREFIX = GroupPlayClassicDelegates.SECRET_SIGNAL_PREFIX
    fun formatPinTheMood(mood: String, hostLabel: String): String = GroupPlayClassicDelegates.formatPinTheMood(mood, hostLabel)
    fun parsePinTheMood(content: String): String? = GroupPlayClassicDelegates.parsePinTheMood(content)
    fun formatRevokeRush(window: String, hostLabel: String): String = GroupPlayClassicDelegates.formatRevokeRush(window, hostLabel)
    fun parseRevokeRush(content: String): String? = GroupPlayClassicDelegates.parseRevokeRush(content)
    fun formatSecretSignal(signal: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSecretSignal(signal, hostLabel)
    fun parseSecretSignal(content: String): String? = GroupPlayClassicDelegates.parseSecretSignal(content)
    const val IDEA_RELAY_PREFIX = GroupPlayClassicDelegates.IDEA_RELAY_PREFIX
    const val TEMPO_TAP_PREFIX = GroupPlayClassicDelegates.TEMPO_TAP_PREFIX
    const val TRANSLATE_RELAY_PREFIX = GroupPlayClassicDelegates.TRANSLATE_RELAY_PREFIX
    fun formatIdeaRelay(seed: String, hostLabel: String): String = GroupPlayClassicDelegates.formatIdeaRelay(seed, hostLabel)
    fun parseIdeaRelay(content: String): String? = GroupPlayClassicDelegates.parseIdeaRelay(content)
    fun formatTempoTap(beat: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTempoTap(beat, hostLabel)
    fun parseTempoTap(content: String): String? = GroupPlayClassicDelegates.parseTempoTap(content)
    fun formatTranslateRelay(pair: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTranslateRelay(pair, hostLabel)
    fun parseTranslateRelay(content: String): String? = GroupPlayClassicDelegates.parseTranslateRelay(content)
    const val INVITE_RACE_PREFIX = GroupPlayClassicDelegates.INVITE_RACE_PREFIX
    const val MENTION_MAYHEM_PREFIX = GroupPlayClassicDelegates.MENTION_MAYHEM_PREFIX
    const val LINK_HUNT_PREFIX = GroupPlayClassicDelegates.LINK_HUNT_PREFIX
    fun formatInviteRace(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatInviteRace(mode, hostLabel)
    fun parseInviteRace(content: String): String? = GroupPlayClassicDelegates.parseInviteRace(content)
    fun formatMentionMayhem(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMentionMayhem(mode, hostLabel)
    fun parseMentionMayhem(content: String): String? = GroupPlayClassicDelegates.parseMentionMayhem(content)
    fun formatLinkHunt(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatLinkHunt(mode, hostLabel)
    fun parseLinkHunt(content: String): String? = GroupPlayClassicDelegates.parseLinkHunt(content)
    const val NUDGE_DASH_PREFIX = GroupPlayClassicDelegates.NUDGE_DASH_PREFIX
    const val CODE_CHECK_PREFIX = GroupPlayClassicDelegates.CODE_CHECK_PREFIX
    const val TRUST_SPRINT_PREFIX = GroupPlayClassicDelegates.TRUST_SPRINT_PREFIX
    fun formatNudgeDash(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatNudgeDash(mode, hostLabel)
    fun parseNudgeDash(content: String): String? = GroupPlayClassicDelegates.parseNudgeDash(content)
    fun formatCodeCheck(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatCodeCheck(mode, hostLabel)
    fun parseCodeCheck(content: String): String? = GroupPlayClassicDelegates.parseCodeCheck(content)
    fun formatTrustSprint(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatTrustSprint(mode, hostLabel)
    fun parseTrustSprint(content: String): String? = GroupPlayClassicDelegates.parseTrustSprint(content)
    const val MOOD_METER_PREFIX = GroupPlayClassicDelegates.MOOD_METER_PREFIX
    const val FOCUS_SPRINT_PREFIX = GroupPlayClassicDelegates.FOCUS_SPRINT_PREFIX
    const val GRATITUDE_ROUND_PREFIX = GroupPlayClassicDelegates.GRATITUDE_ROUND_PREFIX
    fun formatMoodMeter(scale: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMoodMeter(scale, hostLabel)
    fun parseMoodMeter(content: String): String? = GroupPlayClassicDelegates.parseMoodMeter(content)
    fun formatFocusSprint(window: String, hostLabel: String): String = GroupPlayClassicDelegates.formatFocusSprint(window, hostLabel)
    fun parseFocusSprint(content: String): String? = GroupPlayClassicDelegates.parseFocusSprint(content)
    fun formatGratitudeRound(prompt: String, hostLabel: String): String = GroupPlayClassicDelegates.formatGratitudeRound(prompt, hostLabel)
    fun parseGratitudeRound(content: String): String? = GroupPlayClassicDelegates.parseGratitudeRound(content)
    const val QR_QUEST_PREFIX = GroupPlayClassicDelegates.QR_QUEST_PREFIX
    const val CONTACT_SWAP_PREFIX = GroupPlayClassicDelegates.CONTACT_SWAP_PREFIX
    const val SCAN_SPRINT_PREFIX = GroupPlayClassicDelegates.SCAN_SPRINT_PREFIX
    fun formatQrQuest(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatQrQuest(mode, hostLabel)
    fun parseQrQuest(content: String): String? = GroupPlayClassicDelegates.parseQrQuest(content)
    fun formatContactSwap(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatContactSwap(mode, hostLabel)
    fun parseContactSwap(content: String): String? = GroupPlayClassicDelegates.parseContactSwap(content)
    fun formatScanSprint(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatScanSprint(mode, hostLabel)
    fun parseScanSprint(content: String): String? = GroupPlayClassicDelegates.parseScanSprint(content)
    const val SPOILER_RACE_PREFIX = GroupPlayClassicDelegates.SPOILER_RACE_PREFIX
    const val BLUR_BATTLE_PREFIX = GroupPlayClassicDelegates.BLUR_BATTLE_PREFIX
    const val DOWNLOAD_DASH_PREFIX = GroupPlayClassicDelegates.DOWNLOAD_DASH_PREFIX
    fun formatSpoilerRace(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSpoilerRace(mode, hostLabel)
    fun parseSpoilerRace(content: String): String? = GroupPlayClassicDelegates.parseSpoilerRace(content)
    fun formatBlurBattle(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatBlurBattle(mode, hostLabel)
    fun parseBlurBattle(content: String): String? = GroupPlayClassicDelegates.parseBlurBattle(content)
    fun formatDownloadDash(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatDownloadDash(mode, hostLabel)
    fun parseDownloadDash(content: String): String? = GroupPlayClassicDelegates.parseDownloadDash(content)
    const val PIN_DROP_PREFIX = GroupPlayClassicDelegates.PIN_DROP_PREFIX
    const val FILE_RELAY_PREFIX = GroupPlayClassicDelegates.FILE_RELAY_PREFIX
    const val MAP_DASH_PREFIX = GroupPlayClassicDelegates.MAP_DASH_PREFIX
    const val VAULT_LOCK_PREFIX = GroupPlayClassicDelegates.VAULT_LOCK_PREFIX
    const val WATERMARK_HUNT_PREFIX = GroupPlayClassicDelegates.WATERMARK_HUNT_PREFIX
    const val SECURE_SPRINT_PREFIX = GroupPlayClassicDelegates.SECURE_SPRINT_PREFIX
    fun formatPinDrop(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatPinDrop(mode, hostLabel)
    fun parsePinDrop(content: String): String? = GroupPlayClassicDelegates.parsePinDrop(content)
    fun formatFileRelay(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatFileRelay(mode, hostLabel)
    fun parseFileRelay(content: String): String? = GroupPlayClassicDelegates.parseFileRelay(content)
    fun formatMapDash(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatMapDash(mode, hostLabel)
    fun parseMapDash(content: String): String? = GroupPlayClassicDelegates.parseMapDash(content)
    fun formatVaultLock(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatVaultLock(mode, hostLabel)
    fun parseVaultLock(content: String): String? = GroupPlayClassicDelegates.parseVaultLock(content)
    fun formatWatermarkHunt(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatWatermarkHunt(mode, hostLabel)
    fun parseWatermarkHunt(content: String): String? = GroupPlayClassicDelegates.parseWatermarkHunt(content)
    fun formatSecureSprint(mode: String, hostLabel: String): String = GroupPlayClassicDelegates.formatSecureSprint(mode, hostLabel)
    fun parseSecureSprint(content: String): String? = GroupPlayClassicDelegates.parseSecureSprint(content)

    const val PHOTO_RACE_PREFIX = GroupPlayModeDelegates.PHOTO_RACE_PREFIX
    const val CLIP_DASH_PREFIX = GroupPlayModeDelegates.CLIP_DASH_PREFIX
    const val FRAME_HUNT_PREFIX = GroupPlayModeDelegates.FRAME_HUNT_PREFIX
    const val SUMMARY_CIRCLE_PREFIX = GroupPlayModeDelegates.SUMMARY_CIRCLE_PREFIX
    const val REWRITE_RELAY_PREFIX = GroupPlayModeDelegates.REWRITE_RELAY_PREFIX
    const val PROMPT_SPRINT_PREFIX = GroupPlayModeDelegates.PROMPT_SPRINT_PREFIX
    const val SUGGEST_CIRCLE_PREFIX = GroupPlayModeDelegates.SUGGEST_CIRCLE_PREFIX
    const val VOICE_RACE_PREFIX = GroupPlayModeDelegates.VOICE_RACE_PREFIX
    const val REPLY_SPRINT_PREFIX = GroupPlayModeDelegates.REPLY_SPRINT_PREFIX
    const val PIXEL_QUEST_PREFIX = GroupPlayModeDelegates.PIXEL_QUEST_PREFIX
    const val ASSIST_CIRCLE_PREFIX = GroupPlayModeDelegates.ASSIST_CIRCLE_PREFIX
    const val DECISION_DASH_PREFIX = GroupPlayModeDelegates.DECISION_DASH_PREFIX
    const val DOC_HUNT_PREFIX = GroupPlayModeDelegates.DOC_HUNT_PREFIX
    const val MEANING_RACE_PREFIX = GroupPlayModeDelegates.MEANING_RACE_PREFIX
    const val INSIGHT_SPRINT_PREFIX = GroupPlayModeDelegates.INSIGHT_SPRINT_PREFIX
    const val GIF_RELAY_PREFIX = GroupPlayModeDelegates.GIF_RELAY_PREFIX
    const val MARK_HUNT_PREFIX = GroupPlayModeDelegates.MARK_HUNT_PREFIX
    const val LEAK_SPRINT_PREFIX = GroupPlayModeDelegates.LEAK_SPRINT_PREFIX
    const val VOICE_RING_PREFIX = GroupPlayModeDelegates.VOICE_RING_PREFIX
    const val VIDEO_STAGE_PREFIX = GroupPlayModeDelegates.VIDEO_STAGE_PREFIX
    const val RING_DASH_PREFIX = GroupPlayModeDelegates.RING_DASH_PREFIX
    const val WALL_PICK_PREFIX = GroupPlayModeDelegates.WALL_PICK_PREFIX
    const val FONT_RACE_PREFIX = GroupPlayModeDelegates.FONT_RACE_PREFIX
    const val THEME_SPRINT_PREFIX = GroupPlayModeDelegates.THEME_SPRINT_PREFIX
    const val UNREAD_RUSH_PREFIX = GroupPlayModeDelegates.UNREAD_RUSH_PREFIX
    const val RING_CHOIR_PREFIX = GroupPlayModeDelegates.RING_CHOIR_PREFIX
    const val ALERT_SPRINT_PREFIX = GroupPlayModeDelegates.ALERT_SPRINT_PREFIX
    const val SOUND_WAVE_PREFIX = GroupPlayModeDelegates.SOUND_WAVE_PREFIX
    const val PREVIEW_MASK_PREFIX = GroupPlayModeDelegates.PREVIEW_MASK_PREFIX
    const val BEEP_DASH_PREFIX = GroupPlayModeDelegates.BEEP_DASH_PREFIX
    const val PUSH_RACE_PREFIX = GroupPlayModeDelegates.PUSH_RACE_PREFIX
    const val REMIND_CIRCLE_PREFIX = GroupPlayModeDelegates.REMIND_CIRCLE_PREFIX
    const val WAKE_SPRINT_PREFIX = GroupPlayModeDelegates.WAKE_SPRINT_PREFIX
    const val QUIET_HOUR_PREFIX = GroupPlayModeDelegates.QUIET_HOUR_PREFIX
    const val OFFLINE_HINT_PREFIX = GroupPlayModeDelegates.OFFLINE_HINT_PREFIX
    const val FALLBACK_DASH_PREFIX = GroupPlayModeDelegates.FALLBACK_DASH_PREFIX
    const val CLICK_BEAT_PREFIX = GroupPlayModeDelegates.CLICK_BEAT_PREFIX
    const val BUZZ_RELAY_PREFIX = GroupPlayModeDelegates.BUZZ_RELAY_PREFIX
    const val FEEL_SPRINT_PREFIX = GroupPlayModeDelegates.FEEL_SPRINT_PREFIX
    const val SLIDE_RACE_PREFIX = GroupPlayModeDelegates.SLIDE_RACE_PREFIX
    const val FADE_CIRCLE_PREFIX = GroupPlayModeDelegates.FADE_CIRCLE_PREFIX
    const val SPRING_DASH_PREFIX = GroupPlayModeDelegates.SPRING_DASH_PREFIX
    const val SNAP_GUARD_PREFIX = GroupPlayModeDelegates.SNAP_GUARD_PREFIX
    const val RECENTS_HIDE_PREFIX = GroupPlayModeDelegates.RECENTS_HIDE_PREFIX
    const val SHIELD_SPRINT_PREFIX = GroupPlayModeDelegates.SHIELD_SPRINT_PREFIX
    const val COPY_LOCK_PREFIX = GroupPlayModeDelegates.COPY_LOCK_PREFIX
    const val EXPORT_SEAL_PREFIX = GroupPlayModeDelegates.EXPORT_SEAL_PREFIX
    const val LEAK_WALL_PREFIX = GroupPlayModeDelegates.LEAK_WALL_PREFIX
    const val FORWARD_SEAL_PREFIX = GroupPlayModeDelegates.FORWARD_SEAL_PREFIX
    const val CHAT_EXPORT_LOCK_PREFIX = GroupPlayModeDelegates.CHAT_EXPORT_LOCK_PREFIX
    const val VAULT_FENCE_PREFIX = GroupPlayModeDelegates.VAULT_FENCE_PREFIX
    const val SEAL_SPRINT_PREFIX = GroupPlayModeDelegates.SEAL_SPRINT_PREFIX
    const val PQXDH_DASH_PREFIX = GroupPlayModeDelegates.PQXDH_DASH_PREFIX
    const val CERT_RELAY_PREFIX = GroupPlayModeDelegates.CERT_RELAY_PREFIX
    const val MARK_SPRINT_PREFIX = GroupPlayModeDelegates.MARK_SPRINT_PREFIX
    const val FADE_TIMER_PREFIX = GroupPlayModeDelegates.FADE_TIMER_PREFIX
    const val STAMP_RELAY_PREFIX = GroupPlayModeDelegates.STAMP_RELAY_PREFIX
    fun formatPhotoRace(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPhotoRace(mode, hostLabel)
    fun parsePhotoRace(content: String): String? = GroupPlayModeDelegates.parsePhotoRace(content)
    fun formatClipDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatClipDash(mode, hostLabel)
    fun parseClipDash(content: String): String? = GroupPlayModeDelegates.parseClipDash(content)
    fun formatFrameHunt(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFrameHunt(mode, hostLabel)
    fun parseFrameHunt(content: String): String? = GroupPlayModeDelegates.parseFrameHunt(content)
    fun formatSummaryCircle(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSummaryCircle(mode, hostLabel)
    fun parseSummaryCircle(content: String): String? = GroupPlayModeDelegates.parseSummaryCircle(content)
    fun formatRewriteRelay(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatRewriteRelay(mode, hostLabel)
    fun parseRewriteRelay(content: String): String? = GroupPlayModeDelegates.parseRewriteRelay(content)
    fun formatPromptSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPromptSprint(mode, hostLabel)
    fun parsePromptSprint(content: String): String? = GroupPlayModeDelegates.parsePromptSprint(content)
    fun formatSuggestCircle(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSuggestCircle(mode, hostLabel)
    fun parseSuggestCircle(content: String): String? = GroupPlayModeDelegates.parseSuggestCircle(content)
    fun formatVoiceRace(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatVoiceRace(mode, hostLabel)
    fun parseVoiceRace(content: String): String? = GroupPlayModeDelegates.parseVoiceRace(content)
    fun formatReplySprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatReplySprint(mode, hostLabel)
    fun parseReplySprint(content: String): String? = GroupPlayModeDelegates.parseReplySprint(content)
    fun formatPixelQuest(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPixelQuest(mode, hostLabel)
    fun parsePixelQuest(content: String): String? = GroupPlayModeDelegates.parsePixelQuest(content)
    fun parseAssistCircle(content: String): String? = GroupPlayModeDelegates.parseAssistCircle(content)
    fun parseDecisionDash(content: String): String? = GroupPlayModeDelegates.parseDecisionDash(content)
    fun formatDocHunt(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatDocHunt(mode, hostLabel)
    fun parseDocHunt(content: String): String? = GroupPlayModeDelegates.parseDocHunt(content)
    fun parseMeaningRace(content: String): String? = GroupPlayModeDelegates.parseMeaningRace(content)
    fun parseInsightSprint(content: String): String? = GroupPlayModeDelegates.parseInsightSprint(content)
    fun formatGifRelay(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatGifRelay(mode, hostLabel)
    fun parseGifRelay(content: String): String? = GroupPlayModeDelegates.parseGifRelay(content)
    fun formatMarkHunt(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatMarkHunt(mode, hostLabel)
    fun parseMarkHunt(content: String): String? = GroupPlayModeDelegates.parseMarkHunt(content)
    fun formatLeakSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatLeakSprint(mode, hostLabel)
    fun parseLeakSprint(content: String): String? = GroupPlayModeDelegates.parseLeakSprint(content)
    fun formatVoiceRing(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatVoiceRing(mode, hostLabel)
    fun parseVoiceRing(content: String): String? = GroupPlayModeDelegates.parseVoiceRing(content)
    fun formatVideoStage(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatVideoStage(mode, hostLabel)
    fun parseVideoStage(content: String): String? = GroupPlayModeDelegates.parseVideoStage(content)
    fun formatRingDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatRingDash(mode, hostLabel)
    fun parseRingDash(content: String): String? = GroupPlayModeDelegates.parseRingDash(content)
    fun formatWallPick(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatWallPick(mode, hostLabel)
    fun parseWallPick(content: String): String? = GroupPlayModeDelegates.parseWallPick(content)
    fun formatFontRace(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFontRace(mode, hostLabel)
    fun parseFontRace(content: String): String? = GroupPlayModeDelegates.parseFontRace(content)
    fun formatThemeSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatThemeSprint(mode, hostLabel)
    fun parseThemeSprint(content: String): String? = GroupPlayModeDelegates.parseThemeSprint(content)
    fun formatUnreadRush(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatUnreadRush(mode, hostLabel)
    fun parseUnreadRush(content: String): String? = GroupPlayModeDelegates.parseUnreadRush(content)
    fun formatRingChoir(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatRingChoir(mode, hostLabel)
    fun parseRingChoir(content: String): String? = GroupPlayModeDelegates.parseRingChoir(content)
    fun formatAlertSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatAlertSprint(mode, hostLabel)
    fun parseAlertSprint(content: String): String? = GroupPlayModeDelegates.parseAlertSprint(content)
    fun formatSoundWave(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSoundWave(mode, hostLabel)
    fun parseSoundWave(content: String): String? = GroupPlayModeDelegates.parseSoundWave(content)
    fun formatPreviewMask(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPreviewMask(mode, hostLabel)
    fun parsePreviewMask(content: String): String? = GroupPlayModeDelegates.parsePreviewMask(content)
    fun formatBeepDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatBeepDash(mode, hostLabel)
    fun parseBeepDash(content: String): String? = GroupPlayModeDelegates.parseBeepDash(content)
    fun formatPushRace(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPushRace(mode, hostLabel)
    fun parsePushRace(content: String): String? = GroupPlayModeDelegates.parsePushRace(content)
    fun formatRemindCircle(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatRemindCircle(mode, hostLabel)
    fun parseRemindCircle(content: String): String? = GroupPlayModeDelegates.parseRemindCircle(content)
    fun formatWakeSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatWakeSprint(mode, hostLabel)
    fun parseWakeSprint(content: String): String? = GroupPlayModeDelegates.parseWakeSprint(content)
    fun formatQuietHour(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatQuietHour(mode, hostLabel)
    fun parseQuietHour(content: String): String? = GroupPlayModeDelegates.parseQuietHour(content)
    fun formatOfflineHint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatOfflineHint(mode, hostLabel)
    fun parseOfflineHint(content: String): String? = GroupPlayModeDelegates.parseOfflineHint(content)
    fun formatFallbackDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFallbackDash(mode, hostLabel)
    fun parseFallbackDash(content: String): String? = GroupPlayModeDelegates.parseFallbackDash(content)
    fun formatClickBeat(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatClickBeat(mode, hostLabel)
    fun parseClickBeat(content: String): String? = GroupPlayModeDelegates.parseClickBeat(content)
    fun formatBuzzRelay(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatBuzzRelay(mode, hostLabel)
    fun parseBuzzRelay(content: String): String? = GroupPlayModeDelegates.parseBuzzRelay(content)
    fun formatFeelSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFeelSprint(mode, hostLabel)
    fun parseFeelSprint(content: String): String? = GroupPlayModeDelegates.parseFeelSprint(content)
    fun formatSlideRace(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSlideRace(mode, hostLabel)
    fun parseSlideRace(content: String): String? = GroupPlayModeDelegates.parseSlideRace(content)
    fun formatFadeCircle(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFadeCircle(mode, hostLabel)
    fun parseFadeCircle(content: String): String? = GroupPlayModeDelegates.parseFadeCircle(content)
    fun formatSpringDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSpringDash(mode, hostLabel)
    fun parseSpringDash(content: String): String? = GroupPlayModeDelegates.parseSpringDash(content)
    fun formatSnapGuard(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSnapGuard(mode, hostLabel)
    fun parseSnapGuard(content: String): String? = GroupPlayModeDelegates.parseSnapGuard(content)
    fun formatRecentsHide(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatRecentsHide(mode, hostLabel)
    fun parseRecentsHide(content: String): String? = GroupPlayModeDelegates.parseRecentsHide(content)
    fun formatShieldSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatShieldSprint(mode, hostLabel)
    fun parseShieldSprint(content: String): String? = GroupPlayModeDelegates.parseShieldSprint(content)
    fun formatCopyLock(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatCopyLock(mode, hostLabel)
    fun parseCopyLock(content: String): String? = GroupPlayModeDelegates.parseCopyLock(content)
    fun formatExportSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatExportSeal(mode, hostLabel)
    fun parseExportSeal(content: String): String? = GroupPlayModeDelegates.parseExportSeal(content)
    fun formatLeakWall(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatLeakWall(mode, hostLabel)
    fun parseLeakWall(content: String): String? = GroupPlayModeDelegates.parseLeakWall(content)
    fun formatForwardSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatForwardSeal(mode, hostLabel)
    fun parseForwardSeal(content: String): String? = GroupPlayModeDelegates.parseForwardSeal(content)
    fun formatChatExportLock(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatChatExportLock(mode, hostLabel)
    fun parseChatExportLock(content: String): String? = GroupPlayModeDelegates.parseChatExportLock(content)
    fun formatVaultFence(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatVaultFence(mode, hostLabel)
    fun parseVaultFence(content: String): String? = GroupPlayModeDelegates.parseVaultFence(content)
    fun formatSealSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatSealSprint(mode, hostLabel)
    fun parseSealSprint(content: String): String? = GroupPlayModeDelegates.parseSealSprint(content)
    fun formatPqxdhDash(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPqxdhDash(mode, hostLabel)
    fun parsePqxdhDash(content: String): String? = GroupPlayModeDelegates.parsePqxdhDash(content)
    fun formatCertRelay(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatCertRelay(mode, hostLabel)
    fun parseCertRelay(content: String): String? = GroupPlayModeDelegates.parseCertRelay(content)
    fun formatMarkSprint(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatMarkSprint(mode, hostLabel)
    fun parseMarkSprint(content: String): String? = GroupPlayModeDelegates.parseMarkSprint(content)
    fun formatFadeTimer(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatFadeTimer(mode, hostLabel)
    fun parseFadeTimer(content: String): String? = GroupPlayModeDelegates.parseFadeTimer(content)
    fun formatStampRelay(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatStampRelay(mode, hostLabel)
    fun parseStampRelay(content: String): String? = GroupPlayModeDelegates.parseStampRelay(content)
    fun formatLinkLock(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatLinkLock(mode, hostLabel)
    fun parseLinkLock(content: String): String? = GroupPlayModeDelegates.parseLinkLock(content)
    fun formatPreviewMute(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPreviewMute(mode, hostLabel)
    fun parsePreviewMute(content: String): String? = GroupPlayModeDelegates.parsePreviewMute(content)
    fun formatUrlFence(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatUrlFence(mode, hostLabel)
    fun parseUrlFence(content: String): String? = GroupPlayModeDelegates.parseUrlFence(content)
    fun formatNotifMask(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatNotifMask(mode, hostLabel)
    fun parseNotifMask(content: String): String? = GroupPlayModeDelegates.parseNotifMask(content)
    fun formatListBlur(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatListBlur(mode, hostLabel)
    fun parseListBlur(content: String): String? = GroupPlayModeDelegates.parseListBlur(content)
    fun formatTraySeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatTraySeal(mode, hostLabel)
    fun parseTraySeal(content: String): String? = GroupPlayModeDelegates.parseTraySeal(content)
    fun formatReactLock(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatReactLock(mode, hostLabel)
    fun parseReactLock(content: String): String? = GroupPlayModeDelegates.parseReactLock(content)
    fun formatStarSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatStarSeal(mode, hostLabel)
    fun parseStarSeal(content: String): String? = GroupPlayModeDelegates.parseStarSeal(content)
    fun formatMetaFence(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatMetaFence(mode, hostLabel)
    fun parseMetaFence(content: String): String? = GroupPlayModeDelegates.parseMetaFence(content)
    fun formatTypingSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatTypingSeal(mode, hostLabel)
    fun parseTypingSeal(content: String): String? = GroupPlayModeDelegates.parseTypingSeal(content)
    fun formatReadSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatReadSeal(mode, hostLabel)
    fun parseReadSeal(content: String): String? = GroupPlayModeDelegates.parseReadSeal(content)
    fun formatPresenceSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatPresenceSeal(mode, hostLabel)
    fun parsePresenceSeal(content: String): String? = GroupPlayModeDelegates.parsePresenceSeal(content)
    fun formatLastSeenSeal(mode: String, hostLabel: String): String = GroupPlayModeDelegates.formatLastSeenSeal(mode, hostLabel)
    fun parseLastSeenSeal(content: String): String? = GroupPlayModeDelegates.parseLastSeenSeal(content)
}
