package com.maodouchat.util

/**
 * 玩法模式/封印类在 GroupPlayPolicy 上的同名委托：实现在 GroupPlayModePolicy /
 * GroupPlaySealPolicy，前缀与函数签名原样搬到这里，调用方继续走 GroupPlayPolicy 零改动。
 */
internal object GroupPlayModeDelegates {

    const val PHOTO_RACE_PREFIX = "PHOTORACE:"
    const val CLIP_DASH_PREFIX = "CLIPDASH:"
    const val FRAME_HUNT_PREFIX = "FRAMEHUNT:"
    const val SUMMARY_CIRCLE_PREFIX = "SUMCIRCLE:"
    const val REWRITE_RELAY_PREFIX = "REWRITERELAY:"
    const val PROMPT_SPRINT_PREFIX = "PROMPTSPRINT:"
    const val SUGGEST_CIRCLE_PREFIX = "SUGCIRCLE:"
    const val VOICE_RACE_PREFIX = "VOICERACE:"
    const val REPLY_SPRINT_PREFIX = "REPLYSPRINT:"
    const val PIXEL_QUEST_PREFIX = "PIXELQUEST:"
    const val ASSIST_CIRCLE_PREFIX = "ASSISTCIRCLE:"
    const val DECISION_DASH_PREFIX = "DECISIONDASH:"
    const val DOC_HUNT_PREFIX = "DOCHUNT:"
    const val MEANING_RACE_PREFIX = "MEANINGRACE:"
    const val INSIGHT_SPRINT_PREFIX = "INSIGHTSPRINT:"
    const val GIF_RELAY_PREFIX = "GIFRELAY:"
    const val MARK_HUNT_PREFIX = "MARKHUNT:"
    const val LEAK_SPRINT_PREFIX = "LEAKSPRINT:"
    const val VOICE_RING_PREFIX = "VOICERING:"
    const val VIDEO_STAGE_PREFIX = "VIDEOSTAGE:"
    const val RING_DASH_PREFIX = "RINGDASH:"
    const val WALL_PICK_PREFIX = "WALLPICK:"
    const val FONT_RACE_PREFIX = "FONTRACE:"
    const val THEME_SPRINT_PREFIX = "THEMESPRINT:"
    const val UNREAD_RUSH_PREFIX = "UNREADRUSH:"
    const val RING_CHOIR_PREFIX = "RINGCHOIR:"
    const val ALERT_SPRINT_PREFIX = "ALERTSPRINT:"
    const val SOUND_WAVE_PREFIX = "SOUNDWAVE:"
    const val PREVIEW_MASK_PREFIX = "PREVIEWMASK:"
    const val BEEP_DASH_PREFIX = "BEEPDASH:"
    const val PUSH_RACE_PREFIX = "PUSHRACE:"
    const val REMIND_CIRCLE_PREFIX = "REMINDCIRCLE:"
    const val WAKE_SPRINT_PREFIX = "WAKESPRINT:"
    const val QUIET_HOUR_PREFIX = "QUIETHOUR:"
    const val OFFLINE_HINT_PREFIX = "OFFLINEHINT:"
    const val FALLBACK_DASH_PREFIX = "FALLBACKDASH:"
    const val CLICK_BEAT_PREFIX = "CLICKBEAT:"
    const val BUZZ_RELAY_PREFIX = "BUZZRELAY:"
    const val FEEL_SPRINT_PREFIX = "FEELSPRINT:"
    const val SLIDE_RACE_PREFIX = "SLIDERACE:"
    const val FADE_CIRCLE_PREFIX = "FADECIRCLE:"
    const val SPRING_DASH_PREFIX = "SPRINGDASH:"
    const val SNAP_GUARD_PREFIX = "SNAPGUARD:"
    const val RECENTS_HIDE_PREFIX = "RECENTSHIDE:"
    const val SHIELD_SPRINT_PREFIX = "SHIELDSPRINT:"
    const val COPY_LOCK_PREFIX = "COPYLOCK:"
    const val EXPORT_SEAL_PREFIX = "EXPORTSEAL:"
    const val LEAK_WALL_PREFIX = "LEAKWALL:"
    const val FORWARD_SEAL_PREFIX = "FORWARDSEAL:"
    const val CHAT_EXPORT_LOCK_PREFIX = "CHATEXPORTLOCK:"
    const val VAULT_FENCE_PREFIX = "VAULTFENCE:"
    const val SEAL_SPRINT_PREFIX = "SEALSPRINT:"
    const val PQXDH_DASH_PREFIX = "PQXDHDASH:"
    const val CERT_RELAY_PREFIX = "CERTRELAY:"
    const val MARK_SPRINT_PREFIX = "MARKSPRINT:"
    const val FADE_TIMER_PREFIX = "FADETIMER:"
    const val STAMP_RELAY_PREFIX = "STAMPRELAY:"

    fun formatPhotoRace(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPhotoRace(mode, hostLabel)
    fun parsePhotoRace(content: String): String? = GroupPlayModePolicy.parsePhotoRace(content)
    fun formatClipDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatClipDash(mode, hostLabel)
    fun parseClipDash(content: String): String? = GroupPlayModePolicy.parseClipDash(content)
    fun formatFrameHunt(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFrameHunt(mode, hostLabel)
    fun parseFrameHunt(content: String): String? = GroupPlayModePolicy.parseFrameHunt(content)
    fun formatSummaryCircle(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSummaryCircle(mode, hostLabel)
    fun parseSummaryCircle(content: String): String? = GroupPlayModePolicy.parseSummaryCircle(content)
    fun formatRewriteRelay(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatRewriteRelay(mode, hostLabel)
    fun parseRewriteRelay(content: String): String? = GroupPlayModePolicy.parseRewriteRelay(content)
    fun formatPromptSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPromptSprint(mode, hostLabel)
    fun parsePromptSprint(content: String): String? = GroupPlayModePolicy.parsePromptSprint(content)

    fun formatSuggestCircle(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSuggestCircle(mode, hostLabel)
    fun parseSuggestCircle(content: String): String? = GroupPlayModePolicy.parseSuggestCircle(content)
    fun formatVoiceRace(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatVoiceRace(mode, hostLabel)
    fun parseVoiceRace(content: String): String? = GroupPlayModePolicy.parseVoiceRace(content)
    fun formatReplySprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatReplySprint(mode, hostLabel)
    fun parseReplySprint(content: String): String? = GroupPlayModePolicy.parseReplySprint(content)

    fun formatPixelQuest(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPixelQuest(mode, hostLabel)
    fun parsePixelQuest(content: String): String? = GroupPlayModePolicy.parsePixelQuest(content)
    fun parseAssistCircle(content: String): String? = GroupPlayModePolicy.parseAssistCircle(content)
    fun parseDecisionDash(content: String): String? = GroupPlayModePolicy.parseDecisionDash(content)

    fun formatDocHunt(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatDocHunt(mode, hostLabel)
    fun parseDocHunt(content: String): String? = GroupPlayModePolicy.parseDocHunt(content)
    fun parseMeaningRace(content: String): String? = GroupPlayModePolicy.parseMeaningRace(content)
    fun parseInsightSprint(content: String): String? = GroupPlayModePolicy.parseInsightSprint(content)
    fun formatGifRelay(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatGifRelay(mode, hostLabel)
    fun parseGifRelay(content: String): String? = GroupPlayModePolicy.parseGifRelay(content)
    fun formatMarkHunt(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatMarkHunt(mode, hostLabel)
    fun parseMarkHunt(content: String): String? = GroupPlayModePolicy.parseMarkHunt(content)
    fun formatLeakSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatLeakSprint(mode, hostLabel)
    fun parseLeakSprint(content: String): String? = GroupPlayModePolicy.parseLeakSprint(content)
    fun formatVoiceRing(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatVoiceRing(mode, hostLabel)
    fun parseVoiceRing(content: String): String? = GroupPlayModePolicy.parseVoiceRing(content)
    fun formatVideoStage(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatVideoStage(mode, hostLabel)
    fun parseVideoStage(content: String): String? = GroupPlayModePolicy.parseVideoStage(content)
    fun formatRingDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatRingDash(mode, hostLabel)
    fun parseRingDash(content: String): String? = GroupPlayModePolicy.parseRingDash(content)
    fun formatWallPick(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatWallPick(mode, hostLabel)
    fun parseWallPick(content: String): String? = GroupPlayModePolicy.parseWallPick(content)
    fun formatFontRace(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFontRace(mode, hostLabel)
    fun parseFontRace(content: String): String? = GroupPlayModePolicy.parseFontRace(content)
    fun formatThemeSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatThemeSprint(mode, hostLabel)
    fun parseThemeSprint(content: String): String? = GroupPlayModePolicy.parseThemeSprint(content)
    fun formatUnreadRush(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatUnreadRush(mode, hostLabel)
    fun parseUnreadRush(content: String): String? = GroupPlayModePolicy.parseUnreadRush(content)
    fun formatRingChoir(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatRingChoir(mode, hostLabel)
    fun parseRingChoir(content: String): String? = GroupPlayModePolicy.parseRingChoir(content)
    fun formatAlertSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatAlertSprint(mode, hostLabel)
    fun parseAlertSprint(content: String): String? = GroupPlayModePolicy.parseAlertSprint(content)
    fun formatSoundWave(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSoundWave(mode, hostLabel)
    fun parseSoundWave(content: String): String? = GroupPlayModePolicy.parseSoundWave(content)
    fun formatPreviewMask(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPreviewMask(mode, hostLabel)
    fun parsePreviewMask(content: String): String? = GroupPlayModePolicy.parsePreviewMask(content)
    fun formatBeepDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatBeepDash(mode, hostLabel)
    fun parseBeepDash(content: String): String? = GroupPlayModePolicy.parseBeepDash(content)
    fun formatPushRace(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPushRace(mode, hostLabel)
    fun parsePushRace(content: String): String? = GroupPlayModePolicy.parsePushRace(content)
    fun formatRemindCircle(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatRemindCircle(mode, hostLabel)
    fun parseRemindCircle(content: String): String? = GroupPlayModePolicy.parseRemindCircle(content)
    fun formatWakeSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatWakeSprint(mode, hostLabel)
    fun parseWakeSprint(content: String): String? = GroupPlayModePolicy.parseWakeSprint(content)
    fun formatQuietHour(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatQuietHour(mode, hostLabel)
    fun parseQuietHour(content: String): String? = GroupPlayModePolicy.parseQuietHour(content)
    fun formatOfflineHint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatOfflineHint(mode, hostLabel)
    fun parseOfflineHint(content: String): String? = GroupPlayModePolicy.parseOfflineHint(content)
    fun formatFallbackDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFallbackDash(mode, hostLabel)
    fun parseFallbackDash(content: String): String? = GroupPlayModePolicy.parseFallbackDash(content)
    fun formatClickBeat(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatClickBeat(mode, hostLabel)
    fun parseClickBeat(content: String): String? = GroupPlayModePolicy.parseClickBeat(content)
    fun formatBuzzRelay(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatBuzzRelay(mode, hostLabel)
    fun parseBuzzRelay(content: String): String? = GroupPlayModePolicy.parseBuzzRelay(content)
    fun formatFeelSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFeelSprint(mode, hostLabel)
    fun parseFeelSprint(content: String): String? = GroupPlayModePolicy.parseFeelSprint(content)
    fun formatSlideRace(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSlideRace(mode, hostLabel)
    fun parseSlideRace(content: String): String? = GroupPlayModePolicy.parseSlideRace(content)
    fun formatFadeCircle(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFadeCircle(mode, hostLabel)
    fun parseFadeCircle(content: String): String? = GroupPlayModePolicy.parseFadeCircle(content)
    fun formatSpringDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSpringDash(mode, hostLabel)
    fun parseSpringDash(content: String): String? = GroupPlayModePolicy.parseSpringDash(content)
    fun formatSnapGuard(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSnapGuard(mode, hostLabel)
    fun parseSnapGuard(content: String): String? = GroupPlayModePolicy.parseSnapGuard(content)
    fun formatRecentsHide(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatRecentsHide(mode, hostLabel)
    fun parseRecentsHide(content: String): String? = GroupPlayModePolicy.parseRecentsHide(content)
    fun formatShieldSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatShieldSprint(mode, hostLabel)
    fun parseShieldSprint(content: String): String? = GroupPlayModePolicy.parseShieldSprint(content)
    fun formatCopyLock(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatCopyLock(mode, hostLabel)
    fun parseCopyLock(content: String): String? = GroupPlayModePolicy.parseCopyLock(content)
    fun formatExportSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatExportSeal(mode, hostLabel)
    fun parseExportSeal(content: String): String? = GroupPlayModePolicy.parseExportSeal(content)
    fun formatLeakWall(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatLeakWall(mode, hostLabel)
    fun parseLeakWall(content: String): String? = GroupPlayModePolicy.parseLeakWall(content)
    fun formatForwardSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatForwardSeal(mode, hostLabel)
    fun parseForwardSeal(content: String): String? = GroupPlayModePolicy.parseForwardSeal(content)
    fun formatChatExportLock(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatChatExportLock(mode, hostLabel)
    fun parseChatExportLock(content: String): String? = GroupPlayModePolicy.parseChatExportLock(content)
    fun formatVaultFence(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatVaultFence(mode, hostLabel)
    fun parseVaultFence(content: String): String? = GroupPlayModePolicy.parseVaultFence(content)
    fun formatSealSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatSealSprint(mode, hostLabel)
    fun parseSealSprint(content: String): String? = GroupPlayModePolicy.parseSealSprint(content)
    fun formatPqxdhDash(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPqxdhDash(mode, hostLabel)
    fun parsePqxdhDash(content: String): String? = GroupPlayModePolicy.parsePqxdhDash(content)
    fun formatCertRelay(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatCertRelay(mode, hostLabel)
    fun parseCertRelay(content: String): String? = GroupPlayModePolicy.parseCertRelay(content)
    fun formatMarkSprint(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatMarkSprint(mode, hostLabel)
    fun parseMarkSprint(content: String): String? = GroupPlayModePolicy.parseMarkSprint(content)
    fun formatFadeTimer(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatFadeTimer(mode, hostLabel)
    fun parseFadeTimer(content: String): String? = GroupPlayModePolicy.parseFadeTimer(content)
    fun formatStampRelay(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatStampRelay(mode, hostLabel)
    fun parseStampRelay(content: String): String? = GroupPlayModePolicy.parseStampRelay(content)
    fun formatLinkLock(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatLinkLock(mode, hostLabel)
    fun parseLinkLock(content: String): String? = GroupPlayModePolicy.parseLinkLock(content)
    fun formatPreviewMute(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPreviewMute(mode, hostLabel)
    fun parsePreviewMute(content: String): String? = GroupPlayModePolicy.parsePreviewMute(content)
    fun formatUrlFence(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatUrlFence(mode, hostLabel)
    fun parseUrlFence(content: String): String? = GroupPlayModePolicy.parseUrlFence(content)
    fun formatNotifMask(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatNotifMask(mode, hostLabel)
    fun parseNotifMask(content: String): String? = GroupPlayModePolicy.parseNotifMask(content)
    fun formatListBlur(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatListBlur(mode, hostLabel)
    fun parseListBlur(content: String): String? = GroupPlayModePolicy.parseListBlur(content)
    fun formatTraySeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatTraySeal(mode, hostLabel)
    fun parseTraySeal(content: String): String? = GroupPlayModePolicy.parseTraySeal(content)
    fun formatReactLock(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatReactLock(mode, hostLabel)
    fun parseReactLock(content: String): String? = GroupPlayModePolicy.parseReactLock(content)
    fun formatStarSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatStarSeal(mode, hostLabel)
    fun parseStarSeal(content: String): String? = GroupPlayModePolicy.parseStarSeal(content)
    fun formatMetaFence(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatMetaFence(mode, hostLabel)
    fun parseMetaFence(content: String): String? = GroupPlayModePolicy.parseMetaFence(content)
    fun formatTypingSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatTypingSeal(mode, hostLabel)
    fun parseTypingSeal(content: String): String? = GroupPlayModePolicy.parseTypingSeal(content)
    fun formatReadSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatReadSeal(mode, hostLabel)
    fun parseReadSeal(content: String): String? = GroupPlayModePolicy.parseReadSeal(content)
    fun formatPresenceSeal(mode: String, hostLabel: String): String = GroupPlayModePolicy.formatPresenceSeal(mode, hostLabel)
    fun parsePresenceSeal(content: String): String? = GroupPlaySealPolicy.parsePresenceSeal(content)
    fun formatLastSeenSeal(mode: String, hostLabel: String): String = GroupPlaySealPolicy.formatLastSeenSeal(mode, hostLabel)
    fun parseLastSeenSeal(content: String): String? = GroupPlaySealPolicy.parseLastSeenSeal(content)
}
