package com.maodouchat.util

import android.content.Context

/**
 * 运行时功能开关集中表。
 *
 * 合并自原先 98 个结构相同的 *Prefs.kt（同一份 maodou_runtime_flags 文件，
 * 仅 KEY/默认值不同）。读取/写入与旧实现完全等价，零迁移。
 */
object RuntimeFlags {
    private const val PREFS = "maodou_runtime_flags"

    /** 单个开关的键与默认值。 */
    data class Flag(val key: String, val default: Boolean)

    val AI_ANALYZE_FILE: Flag = Flag("ai_analyze_file_enabled", true)
    val AI_ANALYZE_IMAGE: Flag = Flag("ai_analyze_image_enabled", true)
    /** 服务端 AI 总开关（/api/public/status 的 aiEnabled）——false 时折叠全部 AI 入口。 */
    val AI_MASTER: Flag = Flag("ai_master_enabled", true)
    val AI_IMAGE_OCR: Flag = Flag("ai_image_ocr_enabled", true)
    val AI_GROUP_ASSISTANT: Flag = Flag("ai_group_assistant_enabled", true)
    val AI_REWRITE: Flag = Flag("ai_rewrite_enabled", true)
    val AI_SEMANTIC_SEARCH: Flag = Flag("ai_semantic_search_enabled", true)
    val AI_SUGGEST_REPLIES: Flag = Flag("ai_suggest_replies_enabled", true)
    val AI_SUMMARY: Flag = Flag("ai_summary_enabled", true)
    val AI_TRANSCRIBE: Flag = Flag("ai_transcribe_enabled", true)
    val AI_TRANSLATE: Flag = Flag("ai_translate_enabled", true)
    val APP_LOCK: Flag = Flag("app_lock_enabled", true)
    val AUTO_DOWNLOAD: Flag = Flag("auto_download_enabled", true)
    val BLIND_WATERMARK: Flag = Flag("blind_watermark_enabled", true)
    val BLOCK_REPORT: Flag = Flag("block_report_enabled", true)
    val CALLS: Flag = Flag("calls_enabled", true)
    val CAPTURE_ALERT: Flag = Flag("capture_alert_enabled", true)
    val CHAT_ANIMATIONS: Flag = Flag("chat_animations_enabled", true)
    val CHAT_ARCHIVE: Flag = Flag("chat_archive_enabled", true)
    val CHAT_DRAFTS: Flag = Flag("chat_drafts_enabled", true)
    val CHAT_EXPORT: Flag = Flag("chat_export_enabled", true)
    val CHAT_FOLDERS: Flag = Flag("chat_folders_enabled", true)
    val CHAT_FONT_SCALE: Flag = Flag("chat_font_scale_enabled", true)
    val CHAT_LOCK: Flag = Flag("chat_lock_enabled", true)
    val CHAT_MUTE: Flag = Flag("chat_mute_enabled", true)
    val CHAT_PIN: Flag = Flag("chat_pin_enabled", true)
    val CHAT_WALLPAPER: Flag = Flag("chat_wallpaper_enabled", true)
    val CONTACT_CARD: Flag = Flag("contact_card_enabled", true)
    val DISAPPEARING_MESSAGES: Flag = Flag("disappearing_messages_enabled", true)
    val DND: Flag = Flag("dnd_enabled", true)
    val FAKE_CHAT: Flag = Flag("fake_chat_enabled", true)
    val FILE_SHARE: Flag = Flag("file_share_enabled", true)
    val FRIEND_REQUESTS: Flag = Flag("friend_requests_enabled", true)
    val GIF_SEND: Flag = Flag("gif_send_enabled", true)
    val GLOBAL_SEARCH: Flag = Flag("global_search_enabled", true)
    val GROUP_INVITES: Flag = Flag("group_invites_enabled", true)
    val GROUP_PLAY: Flag = Flag("group_play_enabled", true)
    val HAPTICS: Flag = Flag("haptics_enabled", true)
    val IMAGE_SEND: Flag = Flag("image_send_enabled", true)
    val IN_APP_SOUNDS: Flag = Flag("in_app_sounds_enabled", true)
    val LINK_PREVIEW: Flag = Flag("link_preview_enabled", true)
    val LIVE_LOCATION: Flag = Flag("live_location_enabled", true)
    val MARKDOWN: Flag = Flag("markdown_enabled", true)
    val MARKED_UNREAD: Flag = Flag("marked_unread_enabled", true)
    val MEDIA_UPLOAD: Flag = Flag("media_upload_enabled", true)
    val MENTIONS: Flag = Flag("mentions_enabled", true)
    val MESSAGE_EDIT: Flag = Flag("message_edit_enabled", true)
    val MESSAGE_FORWARDING: Flag = Flag("message_forwarding_enabled", true)
    val MESSAGE_PIN: Flag = Flag("message_pin_enabled", true)
    val MESSAGE_REVOKE: Flag = Flag("message_revoke_enabled", true)
    val MESSAGE_STARRING: Flag = Flag("message_starring_enabled", true)
    val NAV_TRANSITIONS: Flag = Flag("nav_transitions_enabled", true)
    val NEARBY: Flag = Flag("nearby_enabled", true)
    val NOTIFICATION_PREVIEW: Flag = Flag("notification_preview_enabled", true)
    val NOTIFICATION_SOUND: Flag = Flag("notification_sound_enabled", true)
    val NUDGE: Flag = Flag("nudge_enabled", true)
    val OFFLINE_AI: Flag = Flag("offline_ai_enabled", true)
    val POLLS: Flag = Flag("polls_enabled", true)
    val POSTS: Flag = Flag("posts_enabled", true)
    val PRESENCE: Flag = Flag("presence_enabled", true)
    val PUSH_NOTIFICATIONS: Flag = Flag("push_notifications_enabled", true)
    val QR_CODE: Flag = Flag("qr_code_enabled", true)
    val REACTIONS: Flag = Flag("reactions_enabled", true)
    val READ_RECEIPTS: Flag = Flag("read_receipts_enabled", true)
    val RECENTS_EXCLUSION: Flag = Flag("recents_exclusion_enabled", true)
    val RINGTONE: Flag = Flag("ringtone_enabled", true)
    val SAFETY_CODE: Flag = Flag("safety_code_enabled", true)
    val SCHEDULED_MESSAGES: Flag = Flag("scheduled_messages_enabled", true)
    val SCREEN_SECURE: Flag = Flag("screen_secure_runtime_enabled", true)
    val SCREENSHOT_DETECT: Flag = Flag("screenshot_detect_enabled", true)
    val SEALED_SENDER: Flag = Flag("sealed_sender_enabled", true)
    val SECRET_AUTO_DISAPPEAR: Flag = Flag("secret_auto_disappear_enabled", true)
    val SECRET_CHAT_EXPORT_BLOCK: Flag = Flag("secret_chat_export_block_enabled", true)
    val SECRET_CHAT: Flag = Flag("secret_chat_enabled", true)
    val SECRET_COPY_BLOCK: Flag = Flag("secret_copy_block_enabled", true)
    val SECRET_EXTERNAL_LINK_BLOCK: Flag = Flag("secret_external_link_block_enabled", true)
    val SECRET_FORWARD_BLOCK: Flag = Flag("secret_forward_block_enabled", true)
    val SECRET_LAST_SEEN_BLOCK: Flag = Flag("secret_last_seen_block_enabled", true)
    val SECRET_LINK_PREVIEW_BLOCK: Flag = Flag("secret_link_preview_block_enabled", true)
    val SECRET_LIST_PREVIEW_BLOCK: Flag = Flag("secret_list_preview_block_enabled", true)
    val SECRET_MEDIA_EXPORT_BLOCK: Flag = Flag("secret_media_export_block_enabled", true)
    val SECRET_NOTIF_PREVIEW_BLOCK: Flag = Flag("secret_notif_preview_block_enabled", true)
    val SECRET_PRESENCE_BLOCK: Flag = Flag("secret_presence_block_enabled", true)
    val SECRET_REACTION_BLOCK: Flag = Flag("secret_reaction_block_enabled", true)
    val SECRET_READ_RECEIPT_BLOCK: Flag = Flag("secret_read_receipt_block_enabled", true)
    val SECRET_STAR_BLOCK: Flag = Flag("secret_star_block_enabled", true)
    val SECRET_TYPING_BLOCK: Flag = Flag("secret_typing_block_enabled", true)
    val SILENT_SEND: Flag = Flag("silent_send_enabled", true)
    val SPOILER_MEDIA: Flag = Flag("spoiler_media_enabled", true)
    val STATIC_LOCATION: Flag = Flag("static_location_enabled", true)
    val STICKERS: Flag = Flag("stickers_enabled", true)
    val TASK_REMINDERS: Flag = Flag("task_reminders_enabled", true)
    val TYPING_INDICATORS: Flag = Flag("typing_indicators_enabled", true)
    val UNREAD_PRIORITY: Flag = Flag("unread_priority_enabled", true)
    val VIDEO_CALL: Flag = Flag("video_call_enabled", true)
    val VIDEO_SEND: Flag = Flag("video_send_enabled", true)
    val VIEW_ONCE: Flag = Flag("view_once_enabled", true)
    /** 可读对角明水印。密聊表面不再绘制；默认关闭，避免与整页盲水印并存。 */
    val VISIBLE_WATERMARK: Flag = Flag("visible_watermark_enabled", false)
    val VOICE_CALL: Flag = Flag("voice_call_enabled", true)
    val VOICE_MESSAGES: Flag = Flag("voice_messages_enabled", true)

    fun isEnabled(context: Context, flag: Flag): Boolean =
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .getBoolean(flag.key, flag.default)

    fun setEnabled(context: Context, flag: Flag, enabled: Boolean) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putBoolean(flag.key, enabled)
            .apply()
    }
}
